#!/bin/bash

# Install global wrapper script for devs CLI development version
set -euo pipefail

echo "🔧 Installing devs-dev wrapper script..."

# Check if we're in the right directory
if [[ ! -f "README.md" ]] || [[ ! -d "packages" ]]; then
    echo "❌ Error: Run this script from the root of the devs repository"
    exit 1
fi

# Get absolute path to CLI package
CLI_DIR="$(pwd)/packages/cli"

# Check if CLI directory exists
if [[ ! -d "$CLI_DIR" ]]; then
    echo "❌ Error: CLI package directory not found at $CLI_DIR"
    exit 1
fi

# Create wrapper script content
WRAPPER_CONTENT="#!/bin/bash
# Wrapper for devs CLI (development version)
# Generated by install-dev-wrapper.sh
DEVS_DIR=\"$CLI_DIR\"
cd \"\$DEVS_DIR\"
VENV_PYTHON=\$(pyenv which python)
cd - > /dev/null
exec \"\$VENV_PYTHON\" -m devs.cli \"\$@\""

# Create temporary wrapper file
TEMP_WRAPPER="/tmp/devs-dev-wrapper"
echo "$WRAPPER_CONTENT" > "$TEMP_WRAPPER"
chmod +x "$TEMP_WRAPPER"

# Install wrapper to /usr/local/bin
TARGET="/usr/local/bin/devs-dev"

if [[ -w "/usr/local/bin" ]]; then
    mv "$TEMP_WRAPPER" "$TARGET"
    echo "✅ Installed devs-dev wrapper to $TARGET"
else
    echo "🔐 Need sudo to install to $TARGET"
    sudo mv "$TEMP_WRAPPER" "$TARGET"
    echo "✅ Installed devs-dev wrapper to $TARGET"
fi

# Test the wrapper
echo ""
echo "🧪 Testing wrapper..."
if command -v devs-dev >/dev/null 2>&1; then
    echo "✅ devs-dev command is available in PATH"
    echo ""
    echo "📋 You can now use:"
    echo "  devs-dev --help"
    echo "  devs-dev start <container-name>"
    echo "  devs-dev vscode <container-name>"
else
    echo "⚠️  devs-dev not found in PATH. You may need to restart your shell."
fi

echo ""
echo "🎉 Dev wrapper installation complete!"